### ISSUE TITLE
Delete Link needs to update the device db as well

### ISSUE THREAD

**Issue by apearson** [apearson/insteon-plm#12]
Device Links DB does not get updated when a PLM link is deleted.

**Comment by apearson** [comment]
Instead of editing the db directly we should use Insteon's built in link and unlink functions

**Comment by PaulWieland** [comment]
In the event of a physical device failure, there has to still be a way to clean up the PLM links. Need to test whether the `unlink` works when the device won't respond.

**Comment by apearson** [comment]
I believe there's a `deleteLink` method that will remove it from PLM.  This won't be automated but could be in the future
