### ISSUE TITLE
API Idea list

### ISSUE THREAD

**Issue by PaulWieland** [apearson/insteon-plm#13]
My goal is to be able to make a GUI in Node-RED that allows you to manage your insteon network. 

In order to do that, I think it's necessary to document a list of use cases or actions that would be needed in order to build a fully functional GUI.

I will try and keep this list updated. If something gets implemented, I'll update the example (and link to the documentation).  If an idea is rejected, I'll explain why.

### Add a new device
User wants to add a new device to their insteon eco system. Give option to ~~factory reset~~  delete the links database of the device before linking it to the PLM. 

```javascript
device = plm.addDevice('hexID', {
    clearAllLinks: true, // erase all the links from the device before linking it to the PLM
    waitForButtonPress: false // wireless devices need a button press to wake them up
});
```
To do: Investigate whether we need to link the groups for Motion Sensors, Leak Sensors, etc where they broadcast other commands (such as dawn/dusk, low battery, heartbeat, etc)

### Get a device
Returns the instance of the device's object

```javascript
device = plm.getDevice('hexID');
```

### Remove a device
User wants to remove a device from the eco system, which means all links which reference the device on all remote devices should be flagged as deleted.

```javascript
plm.removeDevice(device);
```

### Get all devices
Returns an array of instances of all of the devices

```javascript
deviceList = plm.getAllDevices();
```

### Constructor
The constructor should take a hexID and then interrogate the device to find out what it is and what it's current state is.

Depending on the device type, it should emit different events (e.g. `on`|`off` for switches, `motion`, for motion sensors, `open`|`closed` for door sensors, etc). The device should also have properties to keep track of it's current state (e.g. current brightness level, current on/off state).

### ~~Factory reset~~ Clear the link database
This seems to be the only way to completely clear a device's links table, and is required to get a clean slate.

```javascript
device.eraseDB();
```

### Get all links on a device
Return the full list of links that are in the specified device's database. This is also a time intensive task, so include a cache.

``` javascript
device.getLinks(options: {
    reloadCache: true // Get the links from the device instead of from nodeJS memory
});
```
This has been implemented as `SyncLinks()`. No cache option yet.

### Add device as a controller of other devices
Update the device's links database to make it a controller of the list of devices provided. 
Should automatically make devices listed responders?

```javascript
device.makeControllerOf(
    [device2, device3, device4],
    group: 1,
    options: {
        onLevel = 50,
        rampRate = 10,
        button = 0
    }
);
```
### Remove device as controller of specified device
Delete the link in the controller's database. Also delete the corresponding links in the responder's database?

```javascript
device.stopControlling([device3,device4]);
```

### Add device as a responder to other devices
This might be a private method, unless there is a valid use case for having a device be a responder without the other device being a controller. Otherwise we should just automatically call `makeResponderOf` from within `makeControllerOf`.

The makeResponder will make the device respond to commands from the list of devices provided.

```javascript
device.makeResponderOf(
    [device2, device3, device4],
    options: {
        onLevel = 50,
        rampRate = 10,
        button = 0
    }
```

### Remove device as responder to specified devices
Self explanatory

```javascript
device.stopRespondingTo([device3,device4]);
```

### Get the current state of the device
This is to get the current state of the device - is it on/off, what is the brightness level. Motion sensors seem to also be able to send the battery level.

```javascript
device.query();
```

### List available events
This is needed so we can make a NodeRED Node that allows the user to pick which events to subscribe to, which would then trigger a flow. Since each main device type has different capabilities, we need to be able to list which events are available to listen to. 

```javascript
possibleEvents = device.getEvents();
```

## Scenes
TBD

**Comment by apearson** [comment]
Completed: 
- [ ] Add a new device
- [x] Get a device
- [ ] Remove a device
- [ ] Get all devices
- [ ] Constructor
- [ ] Clear the link database
- [x] Get all links on a device
    - device.getLinks() === device.SyncLinks()
- [ ] Add device as a controller of other devices
- [ ] Add device as a responder to other devices
- [ ] Remove device as responder to specified devices
- [x] Get the current state of the device
- [ ] List available events

**Comment by apearson** [comment]
Updating: Get the current state of the device

Status Request on the InsteonBase class will do this or overrides on child classes

**Comment by PaulWieland** [comment]
All of the important items that were on the original idea list have been implemented in one way or another. Closing this for now, will work on documentation of the actual API at a later date.
