### ISSUE TITLE
Add clamp function and use it

### ISSUE THREAD

**Issue by PaulWieland** [apearson/insteon-plm#23]
We need a clamp function added to the utilities.

The existing methods in the device classes that check upper/lower limits should be adapted to use the clamp utility.

- LightOnAtRate
- LightOffAtRate
- setRampRate
- setOnLevel
- setX10Address
- setMomentaryDuration

**Comment by PaulWieland** [comment]
https://github.com/PaulWieland/insteon-plm/commit/aeaa541d1aa666de57e0db5f0736c0559e01d99a

**Comment by apearson** [comment]
Looks good!
