### ISSUE TITLE
Need to timeout requests

### ISSUE THREAD

**Issue by apearson** [apearson/insteon-plm#4]
Requests should not be allowed to take forever

**Comment by PaulWieland** [comment]
~This pattern might work: https://github.com/caolan/async/issues/247#issuecomment-14116377~
Nevermind - I think this only works for items which are pending processing.

**Comment by apearson** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

This looks like the best way to achieve this

**Comment by PaulWieland** [comment]
So each task in the async queue would become a `race` between the insteon command and a timeout timer?

**Comment by apearson** [comment]
Correct

**Comment by apearson** [comment]
Commits: 
ceaaabb
c294d62

Should implement timeouts for the modem and Insteon devices
